[workspace]
resolver = "2"
members = [
  "libsql",
  "libsql-ffi",
  "libsql-sys",
  "xtask",
]

exclude = [
    "./libsql-sqlite3/ext/crr",
    "./libsql-sqlite3/ext/libsql-wasi",
    "libsql-shell",
    "tools/rebuild-log",
    "tools/fuzz",
]

[workspace.package]
version = "0.9.30"
authors = ["the libSQL authors"]
edition = "2021"
license = "MIT"
repository = "https://github.com/tursodatabase/libsql"

[workspace.dependencies]
zerocopy = { version = "0.7.32", features = ["derive", "alloc"] }

[profile.release]
codegen-units = 1
panic = "unwind"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
