[package]
name = "libsql"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "The libSQL database library"

[dependencies]
tracing = { version = "0.1.37", default-features = false }
thiserror = "1.0.40"

futures = { version = "0.3.28", optional = true }
libsql-sys = { path = "../libsql-sys", optional = true, default-features = true }

parking_lot = { version = "0.12.1", optional = true }

base64 = { version = "0.21", optional = true }
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", features = ["float_roundtrip"], optional = true }
async-trait = "0.1"
bitflags = { version = "2.4.0", optional = true }
worker = { version = "0.6.7", optional = true }

anyhow = { version = "1.0.71", optional = true }
bytes = { version = "1.4.0", features = ["serde"], optional = true }
uuid = { version = "1.4.0", features = ["v4", "serde"], optional = true }
zerocopy = { version = "0.7.28", optional = true }

async-stream = { version = "0.3.5", optional = true }

crc32fast = { version = "1", optional = true }
chrono = { version = "0.4", optional = true }

blocking = "1.6"

[dev-dependencies]
libsql = { path = ".", features = ["serde", "encryption"] }
criterion = { version = "0.5", features = ["html_reports", "async", "async_futures", "async_tokio"] }
pprof = { version = "0.14.0", features = ["criterion", "flamegraph"] }
tokio = { version = "1.29.1", features = ["full"] }
tokio-test = "0.4"
tracing-subscriber = "0.3"
tempfile = { version = "3.7.0" }
rand = "0.8.5"

[features]
default = ["core", "stream", "encryption"]
core = [
  "libsql-sys",
  "dep:bitflags",
  "dep:bytes",
  "dep:futures",
  "dep:parking_lot",
]
stream = [
  "dep:futures",
  "dep:async-stream"
]
serde = ["dep:serde"]
encryption = ["core", "libsql-sys/encryption", "dep:bytes"]

[[bench]]
name = "benchmark"
harness = false

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[package.metadata.cargo-udeps.ignore]
normal = ["hyper-rustls"]
